[package]
name = "c_minus_lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
c_minus_token = { path = "../c-minus-token" }

[[example]]
name = "simple"
path = "./examples/simple.rs"

[features]
regex = []

